version: '3.8'

services:
  gateway:
    image: gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - cart
      - checkout
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  cart:
    image: cart:latest
    expose:
      - "8081"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  checkout:
    image: checkout:latest
    expose:
      - "8082"
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - checkoutdb
    env_file:
      - ./checkout/.env

  checkoutdb:
    container_name: checkoutdb
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: "checkoutdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123123"
    ports:
      - "0.0.0.0:5433:5432" # Bind to all interfaces on the host