version: '3.8'

services:
  cartsdb-local:
    container_name: cartsdb-local
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: "cartsdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123123"
    ports:
      - "0.0.0.0:5432:5432" # Bind to all interfaces on the host

  pgadmin-local:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin4-cart-local
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@db.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: "80"
    ports:
      - "0.0.0.0:16545:80" # Bind to all interfaces on the host
    depends_on:
      - cartsdb-local