name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests
        run: mvn clean install

      - name: Generate test coverage report
        run: mvn jacoco:report

      - name: Upload test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: target/site/jacoco

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker images
        run: |
          docker build -t gateway:latest gateway
          docker build -t cart:latest cart
          docker build -t checkout:latest checkout

      - name: Start services
        run: docker-compose up -d

      - name: Check gateway health endpoint
        run: |
          sleep 30
          curl --fail http://localhost:8080/actuator/health

      - name: Check cart health endpoint
        run: |
          sleep 30
          curl --fail http://localhost:8081/actuator/health

      - name: Check checkout health endpoint
        run: |
          sleep 30
          curl --fail http://localhost:8082/actuator/health