name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  generic-build:
    name: Check building step
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests
        run: mvn clean install

  jacoco-gateway:
    name: Gen Gateway test report
    runs-on: ubuntu-latest
    needs: generic-build
    if: ${{ needs.generic-build.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate JaCoCo report for gateway
        run: mvn -pl gateway jacoco:report

      - name: Upload JaCoCo report for gateway
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-gateway
          path: gateway/target/site/jacoco

  jacoco-cart:
    name: Gen Cart test report
    runs-on: ubuntu-latest
    needs: generic-build
    if: ${{ needs.generic-build.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate JaCoCo report for cart
        run: mvn -pl cart jacoco:report

      - name: Upload JaCoCo report for cart
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-cart
          path: cart/target/site/jacoco

  jacoco-checkout:
    name: Gen Checkout test report
    runs-on: ubuntu-latest
    needs: generic-build
    if: ${{ needs.generic-build.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Generate JaCoCo report for checkout
        run: mvn -pl checkout jacoco:report

      - name: Upload JaCoCo report for checkout
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-checkout
          path: checkout/target/site/jacoco

  health-checks:
    name: Check if only gateway is exposed
    runs-on: ubuntu-latest
    needs: generic-build
    if: ${{ needs.generic-build.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies and run tests
        run: mvn clean install

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Build Docker images
        run: |
          docker build -t gateway:latest gateway
          docker build -t cart:latest cart
          docker build -t checkout:latest checkout

      - name: Start services
        run: docker-compose up -d

      - name: Check gateway health endpoint
        run: |
          sleep 30
          curl --fail http://localhost:8080/actuator/health

      - name: Check cart health endpoint
        run: |
          sleep 30
          if curl --fail http://localhost:8081/actuator/health; then
            echo "App must only be available thru gateway"
            exit 1
          else
            echo "Connection refused as expected"
          fi

      - name: Check checkout health endpoint
        run: |
          sleep 30
          if curl --fail http://localhost:8082/actuator/health; then
            echo "App must only be available thru gateway"
            exit 1
          else
            echo "Connection refused as expected"
          fi